### ISSUE TITLE
希望给出TaiChi_OS的docker run或docker compose安装命令

### ISSUE THREAD

**Issue by ReddotCleaner** [Xingsandesu/TaiChi_OS#1]
希望给出TaiChi_OS的docker run或docker compose安装命令，感谢开源！

**Comment by ReddotCleaner** [comment]
我尝试了一下，把端口80映射出来，以及映射好docker.sock之后，容器正常运行了。也出现了一些运行中的容器，识别到的容器点击可以直接跳转web页面，好评！
![image](https://github.com/Xingsandesu/TaiChi_OS/assets/34325738/6aaea90d-af2d-4d97-a1fe-0e238c0c3c07)

**Comment by ReddotCleaner** [comment]
在```get-taichi.sh```里面找到了，谢谢

**Comment by Xingsandesu** [comment]
get-taichi.sh都有
